### ISSUE TITLE
Cannot draw tickets because of out of gas

### ISSUE THREAD

**Issue by TobyIO** [AlphaX-IBS/ax-raffle#17] opened 2018-10-06 17:23 UTC

**Comment by dennisd74** [comment] 2018-10-08 11:44
The cause is related to value assignment from memory to storage array in solidity.
It will get error when we assign memory array to storage array directly like
storage array A = memory array B;
So we must change this process by pushing memory element directly to storage array A as
storage array A.push(element memory B[x]);
=> That's fixed now.

**Closed as completed by dennisd74** 2018-10-08 11:44 UTC
Labels: bug
